extends Node

enum TRANSITION_STATUS { NONE = -1, LEVEL_UP = 0, DEAD_HUNGRY, DEAD_TIRED, WIN_GAME, MENU }
enum DIR { NONE, UP, DOWN, LEFT, RIGHT }
enum FLIP {  NONE, H, V , BOTH , KEEP }
enum OBJECT_TYPE { UNKNOWN=-1,ACTOR=0, BLOCK, ITEM }

var DIRS_MAP:={Vector2.UP:"Up",Vector2.DOWN:"Down",Vector2.RIGHT:"Right",Vector2.LEFT:"Left"}

enum ITEM_USE_RESULT { STORE, NOT_USED, APPLYED }

enum ITEMS { 	
				ANKH=1, 
				JAR,
				FOOD,
				TORCH,
				MAP,
				ANY_GOD_SIGN,
				GOD_SIGN_GOOD,
				GOD_SIGN_BAD,
				PLAYER_REMAINS 
			}

enum BLOCKS { 	
				EXIT=1,
				ANY_BREAKABLE,
				ANY_GOD_SIGN_BLOCK,
				GOD_SIGN_BLOCK_GOOD,
				GOD_SIGN_BLOCK_BAD,
				FORCE_FIELD,
				FAKE_WALL,
				ANY_EXPLODABLE,
				ANY_SOLID_BLOCK,
				TELEPORTER,
				BREAKABLE_WALL
			 }

enum ACTORS {	
				ANY_ACTOR=1,
				ANY_ENEMY,
				MUMMY,
				GHOST, 
				PLAYER_ONE, 
				PLAYER_TWO, 
				ANY_PLAYER, 
				ANY_RUNNER, 
				CRUSHER_BLOCK, 
				MOBILE_WALL, 
				SCARAB, 
				BOMB #10 
			}

enum BEHAVIORS { HIT, PUSH, USE_IN_PLACE, PICKUP, STEP_ON, CAN_BE_DESTROYED, EXPLODER }
