extends Node

enum TRANSITION_STATUS { NONE = -1, LEVEL_UP = 0, DEAD_HUNGRY, DEAD_TIRED, WIN_GAME, MENU }
enum DIR { NONE, UP, DOWN, LEFT, RIGHT }
enum FLIP {  NONE, H, V , BOTH , KEEP }
enum OBJECT_TYPE { UNKNOWN=-1,ACTOR=0, BLOCK, ITEM }

var DIRS_MAP:={Vector2.UP:"Up",Vector2.DOWN:"Down",Vector2.RIGHT:"Right",Vector2.LEFT:"Left"}

enum ITEM_USE_RESULT { STORE, NOT_USED, APPLYED }

enum ITEMS { MEDKIT=1, SODA, FOOD, TORCH, ANKH, MAP }

var ITEMS_MAP := { 
	ITEMS.MEDKIT:"Medkit*", 
	ITEMS.SODA:"Soda*", 
	ITEMS.FOOD:"Food*", 
	ITEMS.TORCH:"Torch*", 
	ITEMS.ANKH:"Ankh*",
	ITEMS.MAP:"Map*"
}

enum BLOCKS { EXIT=1 }

var BLOCKS_MAP := {
	BLOCKS.EXIT:"Exit*"
}

enum ACTORS { ANY_ENEMY=1, PLAYER_ONE, PLAYER_TWO, ANY_PLAYER, CRUSHER_BLOCK, BLOCK, SCARAB }

var ACTORS_MAP:={ 
	ACTORS.ANY_ENEMY:"Enemy*",
	ACTORS.PLAYER_ONE:"PlayerOne",
	ACTORS.PLAYER_TWO:"PlayerTwo",
	ACTORS.ANY_PLAYER:"Player*",
	ACTORS.CRUSHER_BLOCK:"CrusherBlock*",
	ACTORS.BLOCK:"Block*",
	ACTORS.SCARAB:"Scarab*"
}
